mysqlpiwigo:
   image: mysql:5.5
   container_name: mysql
   volumes:
      - /home/hualinsu/piwigo/mysql/:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
   environment:
      - MYSQL_ROOT_PASSWORD=piwigo
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=piwigo
      - MYSQL_PASSWORD=piwigo
piwigo:
   image: mathieuruellan/piwigo
   container_name: piwigo
   privileged: true
   links:
      - mysqlpiwigo:mysql 
   volumes:
      - /home/hualinsu/piwigo/data/galleries:/var/www/galleries
      - /home/hualinsu/piwigo/data/local:/var/www/local
      - /home/hualinsu/piwigo/data/plugins:/var/www/plugins
      - /home/hualinsu/piwigo/data/themes:/var/www/themes
      - /home/hualinsu/piwigo/cache:/var/www/_data/i
      - /home/hualinsu/piwigo/upload:/var/www/upload"
      - /var/log
      - /var/log/piwigo:/var/log/apache2
   ports:
      - "11280:80"
   hostname: piwigo
   domainname: ourlab.xin

owncloud-server:
  image: owncloud:latest
  container_name: oc
  privileged: true
  links:
      - mysqlpiwigo:mysql 
  volumes:
    - /srv/homeServer/owc/apps:/var/www/html/apps
    - /srv/homeServer/owc/config:/var/www/html/config  
    - /srv/homeServer/owc/data:/var/www/html/data
    - /etc/localtime:/etc/localtime:ro
    - /var/log
    - /var/log/owncloud:/var/log/apache2

  ports:
    - "11380:80"
    - "11443:443"
  hostname: owncloud
  domainname: ourlab.xin

